### ISSUE TITLE
Resource Hints on non <link> elements

### ISSUE THREAD

**Issue by igrigorik** [w3c/resource-hints#1]
(Moved from https://github.com/igrigorik/resource-hints/issues/10)

> The prefetch keyword may be used with link, a, and area elements. [1]

Consider whether it makes sense to expose this for RH, on which elements, and what the motivating use cases are.

[1] http://www.w3.org/TR/html5/links.html#link-type-prefetch

**Comment by igrigorik** [comment]
`prefetch` keyword on `a` + `area` elements is shorthand for: 

``` html
<link rel="preload" href=... as="html" loadpolicy="next inert">
```

As such, UA can automatically translate existing `prefetch` keyword to above policy. Given that this is pure syntax sugar, I don't think this is a high value feature. Closing for now, we can revisit in the future if there is high demand.

**Comment by chicheng** [comment]
Isn't `<a rel="next prefetch" href="page-2.html">Next page</a>` much easier to write manually or implement in CMS than a separate `link` element? Or people may forget to delete `<link rel="dns-prefetch" href="...">` after they removed related `a` element (which may be hundreds of lines away)
