### ISSUE TITLE
Obtaining a resource

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/resource-hints#10]
Spec says: 

> Once the attempt to obtain the hint-initiated resource is complete, the user agent MUST, if the fetch was successful, queue a task to fire a simple event named `load` at the `link` element, or, if the fetch failed to complete for any reason, queue a task to fire a simple event named `error` at the `link` element.

I think it should not monkey patch. It should just "[obtain a resource](https://html.spec.whatwg.org/multipage/semantics.html#concept-link-obtain) as per [[!HTML]]". I believe that will give you the events too.

**Comment by igrigorik** [comment]
Ah, you're right, good call. The one difference here is that we intentionally require that the load does not block the load event -- but I think we can just carve that out.

**Comment by marcoscaceres** [comment]
Yes, you can just add that explicitly. We did the same with manifest:  

> "The steps for obtaining a manifest are given by the following algorithm. The algorithm, if successful, returns a processed manifest. In running these steps, a user agent MUST NOT delay the load event. ... _obtain a resource_ as per [HTML]. " - https://w3c.github.io/manifest/#obtaining

**Comment by igrigorik** [comment]
@marcoscaceres I believe this should be addressed via 6f2d5c4 & 5e2ecc9. Closing, feel free to reopen if it needs more work.
