### ISSUE TITLE
Archive this

### ISSUE THREAD

**Issue by yoavweiss** [w3c/resource-hints#100]
https://github.com/whatwg/html/issues/8949 rightfully points out that this has been successfully integrated into HTML and hence should be archived.

I wondering regarding the best option to do this:
1) We could redirect links to the current spec to https://html.spec.whatwg.org/multipage/links.html#link-type-preconnect (or dns-prefetch, or prefetch), but that would be somewhat lossy. Maybe it's possible to add a note to HTML that links to all those different features, recognizes they were historically tied together, and then we can redirect to that link?
2) We could publish this document as a note, removing most of its content and pointing to the right places in HTML. We could also keep the use-cases section in that case, if folks find that useful.

^^ @noamr @domenic @caribouW3 @nicjansma

**Comment by domenic** [comment]
I would strongly prefer (1). I've found that leaving any non-normative text in other locations, at least if it looks like a spec instead of an explainer, leads to confusion. That's what I've worked to do in other incubations and upstreaming.

I'd suggest just redirecting to https://html.spec.whatwg.org/multipage/links.html#linkTypes . I don't think it's that useful to note that historically some link types were in another document, but if you think so we could maybe put that in https://html.spec.whatwg.org/multipage/acknowledgements.html .

**Comment by caribouW3** [comment]
We can publish as discontinued and have the same thing as for preload.
(see https://www.w3.org/TR/2022/DISC-preload-20220331/ , the latest link redirects automatically)

**Comment by yoavweiss** [comment]
SGTM! I guess redirecting to linkTypes would be good enough.

**Comment by caribouW3** [comment]
Originally tracked in https://github.com/w3c/whatwg-coord/issues/6

**Comment by noamr** [comment]
Apart from within the HTML spec itself, the only link into resource hints is from the [SXG spec](https://wicg.github.io/webpackage/loading.html), which I'm not sure if actively maintained (?)

So perhaps removing the references from HTML is enough?

**Comment by yoavweiss** [comment]
We can remove the references from both HTML and SXG (which seems [active](https://github.com/WICG/webpackage/commits/main)), but need a redirect anyway (in case folks have links that linger).

**Comment by caribouW3** [comment]
https://www.w3.org/TR/2023/DISC-resource-hints-20230314/Overview.html  has been published

**Comment by domenic** [comment]
Thanks, that's a good start! Can you either redirect (best) or empty of content https://www.w3.org/TR/resource-hints/ , like all the other specs listed in https://wiki.whatwg.org/wiki/Fork_tracking ?
