### ISSUE TITLE
New attributes need WebIDL interfaces

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/resource-hints#11]
Specifying new HTML attributes means that new IDL attributes will be needed on the HTMLLinkElement interface.

**Comment by ashumeow** [comment]
WebIDL - HTMLLinkElement interface -- 
http://dxr.mozilla.org/mozilla-central/source/dom/webidl/HTMLLinkElement.webidl

References:- 
https://html.spec.whatwg.org/#the-link-element
https://html.spec.whatwg.org/#other-elements,-attributes-and-apis
