### ISSUE TITLE
Conformance section and classes missing 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/resource-hints#12]
The document should have a conformance section, and it should list both "user agent" and "optimization service" as a conformance class. 

i.e.:

There are two classes of product that can claim conformance to this specification: 
- a `<dfn>user agent</dfn>`. 
- a `<dfn>optimization service</dfn>`.

**Comment by igrigorik** [comment]
@marcoscaceres thanks added the missing section. That said, I only listed "user agent", it's not clear to me how/why "optimization service" can claim conformance here?

**Comment by marcoscaceres** [comment]
Can't recall why I listed "optimization service"... maybe it was something that was previously in the spec? In any case, looking again you are correct - no need to list optimization service. Thanks for adding the conformance class!
