### ISSUE TITLE
Clarify `preload` with relation to `async` and `defer`? 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/resource-hints#13]
The spec says: 

> The <a title="preload">preload hint</a> can be used by the application to initiate early fetch, but delay processing of the received response - e.g. fetch a CSS stylesheet and apply it at some later time, fetch a JavaScript asset and execute it later, and so on. Preload fetches do not block the document `load` event and allow the application to determine which resources are applied, when they are executed, and in which order.

Maybe clarify how this differs from `async` and `defer` in the case of scripts?

**Comment by ashumeow** [comment]
The "async" preloads during HTML parsing and will pause the HTML parser to execute it when it has finished.
The "defer" preloads during HTML parsing and will only execute it after the parser has completed.
("it" refers to data that could in the form of text, images, audio, video)

**Comment by marcoscaceres** [comment]
@ashumeow, I was hoping to see something like what you wrote in the spec itself (in non-normative prose) - in that it clarifies what this spec brings to the table :)

**Comment by ashumeow** [comment]
@marcoscaceres Thanks bro! :)

**Comment by igrigorik** [comment]
This text now lives in `preload`, which should address above feedback: http://w3c.github.io/preload/#early-fetch-and-application-defined-execution

**Comment by Legends** [comment]
@ashumeow This means, in case of scripts `defer `equals `preload` ?

**Comment by torian257x** [comment]
> @ashumeow This means, in case of scripts `defer `equals `preload` ?

afaik yes.... just that preload doesn't have a useful fallback. Bummer.

**Comment by AliN11** [comment]
> @ashumeow This means, in case of scripts `defer `equals `preload` ?

I don't think so. `defer` scripts are executed immediately after DOM is parsed. `preload` doesn't guaranty that.
