### ISSUE TITLE
2.2 Preload doesn't explain when a preload is actually initiated

### ISSUE THREAD

**Issue by smaug----** [w3c/resource-hints#18]
Does creating element and setting the right attributes to it initiate a preload?
Or does the element need to be added to document?

What about if it is in shadow DOM ?
(This one would be related to https://www.w3.org/Bugs/Public/show_bug.cgi?id=26365)

**Comment by igrigorik** [comment]
Closing, addressed in 6f2d5c4 & 5e2ecc9.
