### ISSUE TITLE
Matching hint responses with requests

### ISSUE THREAD

**Issue by igrigorik** [w3c/resource-hints#2]
Continuation of: https://github.com/igrigorik/resource-hints/issues/5. For background see:

http://w3c.github.io/resource-hints/#matching-hint-responses-with-requests

**Comment by igrigorik** [comment]
Closing, this is a preload-specific bug for which we have note in the spec: 
http://w3c.github.io/preload/#matching-responses-with-requests

**Comment by yoavweiss** [comment]
What happens when prefetching a non-cacheable resource? (I'm assuming that since prerender opens a hidden tab, non-cacheable resources would work just fine there)
