### ISSUE TITLE
Conformance requirement in note

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/resource-hints#20]
spec says:

> To ensure compatibility and improve the success rate of prerendering requests the target page **should** use the [[PAGE-VISIBILITY]] to determine the visibility state of the page as it is being rendered and implement appropriate logic to avoid actions that may cause the preload to be abandoned (e.g. non-idempotent requests), or unwanted side-effects from being triggered (e.g. analytics beacons firing prior to the page being displayed).

Because of the SHOULD there, that reads like a conformance requirement.

**Comment by igrigorik** [comment]
s/should/can?

**Comment by marcoscaceres** [comment]
Can wfm
