### ISSUE TITLE
New attributes as Link extensions?

### ISSUE THREAD

**Issue by yoavweiss** [w3c/resource-hints#22]
`as`, `loadpolicy` and `pr` are not part of the "official" attributes mentioned in [the Web Linking spec](https://tools.ietf.org/html/rfc5988#page-6), but can be serialized as `link-extension`s.

Is that a problem? Should we try to add them to the Web linking spec in some way?

AFAICT, there are no practical applications to the fact that they are extensions, so I'm really not sure it's an issue, but I wanted to bring it up, to make sure it isn't.

**Comment by igrigorik** [comment]
It seems like a huge waste of bytes to encode a full URL as rel-type (aka, extension), and updating the spec also seems like an unnecessary burden. Personally, I'd leave this as is until someone has an objection to it - closing. Please feel free to reopen if you (or anyone else) feels strongly about it.
