### ISSUE TITLE
Link headers in non-HTML contexts 

### ISSUE THREAD

**Issue by yoavweiss** [w3c/resource-hints#23]
Do we want to enable `preconnects`/`preloads` when sent as `Link:` headers along with non-HTML resources? What about 3rd party frames?

Are there security implications to enabling that?

If not, we probably want to enable it, but we should be explicit about it.

**Comment by igrigorik** [comment]
Yes, this was always implicit in my mind and I never intended to restrict it to just "main frame navigations" or some such.. e.g. CSS file may want to emit preconnect+preload hints for referenced resources, a JS library can do the same for its dependencies or related resources, etc.

I don't think there is any language restricting this behavior in the spec, so I'm not sure this is something we need to be "explicit" about?

**Comment by yoavweiss** [comment]
You're right that there's nothing restricting that behavior, so no normative text is needed.

However, a note can help to make sure implementations would be aligned on this. (e.g. In my initial patch, for some reason, I enabled it only on HTML resources :) )

**Comment by yoavweiss** [comment]
Thinking about it, such a note doesn't belong here, but in RFC 5988. Closing.
