### ISSUE TITLE
Appropriate time to obtain a resource?

### ISSUE THREAD

**Issue by igrigorik** [w3c/resource-hints#25]
> "the application may dynamically insert and remove additional preload relations via JavaScript."
> 
> That doesn't really mean anything. Is creating a new link element with right attributes an insertion?
> Is inserting such link element to random DOM subtree (which isn't in Document) such insertion?
> or what? - [Olli Pettay](https://bugzilla.mozilla.org/show_bug.cgi?id=1134648#c9)

**Comment by igrigorik** [comment]
Looking at some of the existing specs...

> The appropriate time to obtain the resource is when the external resource link is created or when its element is inserted into a document, whichever happens last - [import spec](http://www.w3.org/TR/html-imports/#link-type-import)
> 
> A user agent that obtains images immediately must synchronously update the image data of an img element, with the restart animation flag set if so stated, whenever that element is created or has experienced relevant mutations... The relevant mutations for an img element: the element's src, srcset or sizes attributes are set, changed, or removed - [img/picture spec](http://www.w3.org/html/wg/drafts/html/master/#relevant-mutations)
> 
> The appropriate times to obtain the rel=stylesheet resource are ([spec](http://www.w3.org/TR/html5/links.html#link-type-stylesheet)):
> - When the external resource link's link element is inserted into a document.
> - When the external resource link is created on a link element that is already in a Document.
> - When the href attribute of the link element of an external resource link that is already in a Document is changed.
> 
> When Chrome encounters the <link> element it will consider prerendering the linked page. This may happen when parsing the page, or later if the link element is dynamically inserted into the document via JavaScript - [prerender whitepaper](https://developers.google.com/chrome/whitepapers/prerender)

In short, the logic is all over... seems like it would be nice to clean this up and have consistent behavior, as this forest is near-impossible to navigate as a developer? E.g. setting src on an image or import relation element might initiate immediate download, but stylesheet and prerender relations elements must also be inserted into a document? Ideally, we want...
1. Consistent behavior for when fetch is initiated
2. Defined behavior for mutations to the element:
   - When src (or equivalent) is updated with a different URI
   - When src (or equivalent) is removed or set to an empty value

### Questions
1. Are there concrete use cases and/or reason for why we need to require an element to be [inserted into a document](https://html.spec.whatwg.org/multipage/infrastructure.html#insert-an-element-into-a-document) to initiate the fetch? Why do some elements skip this?
2. What happens when an element is removed from the document? Should the fetch be cancelled?
3. What happens when an element is reinserted into the document? 
   - E.g. application detaches a subtree to make a set of modifications an reinserts it back into the DOM to minimize reflow, etc. This case seems to indicate that we shouldn't treat "removed from document" as a signal to cancel the fetch? Instead, we should cancel in response to mutations on the element itself - e.g. `src` (or equivalent) is removed or its value is set to an empty value.

**Comment by smaug----** [comment]
(import spec draft isn't perhaps a good spec to refer here, given that it is not clear what the spec will look like eventually. Also, all of in-document handling in web components is still very messy.)

Since we're dealing with <link> elements here, for the consistency I'd expect all rel=foo to behave the same way. So need to compare to img or audio elements.
And is there any reason why one would start the preload/connect/foo when <link> element isn't in
document?
1. is interesting question. Maybe? Or perhaps create rel=preFoo are just hints and processed once
   and since they don't affect to the page itself, there isn't need to cancel.
2. well if the UA just did a preFoo thing, perhaps it doesn't need to do the same thing again since
   the result of the first preFoo is still cached. Similar to <img> elements and setting its src.

Anyhow, the most important thing is to specify how this all works. There are possibly some
less interesting details, where the spec author just needs to choose some behavior - but that
'some behavior' must be spec'ed properly.

**Comment by igrigorik** [comment]
Personally I find the "link elements have own behavior, no need to compare them to img, audio, etc." argument not very compelling.. It makes sense from individual spec author's point of view, but it's a disaster for developers, who now have to learn and account for different behaviors on every element. 

Re, there isn't a need to cancel: there is. With rel=preload we have 'MUST' semantics for UA behavior, and UA must cancel preload fetches which are no longer needed.

**Comment by smaug----** [comment]
I would say it is Img and Audio which have their special handling.
(and one can create img element using 'new Image()' syntax and audio element using 'new Audio()'. They are special, at least atm.)
Normally things work when element is in document. say, iframe is loaded only when it is in document.

preload case... hmm, the spec doesn't say there would be any cancelling happening.
If cancelling should happen in one rel=pre*foo case, I guess it should for consistency happen in all the cases when element is removed from document.

**Comment by igrigorik** [comment]
> (and one can create img element using 'new Image()' syntax and audio element using 'new Audio()'. They are special, at least atm.)

Fair enough. In which case, removing the `src/href` attribute or clearing its value should cancel the fetch... and that also seems like a reasonable behavior for all other elements as well. The trouble with "removed from document > cancel" is that I could be detaching a subtree only to reattach it moments later (e.g. to minimize reflows). 

I'll put together a pull to cover these behaviors in preload+resource hints, but roughly I'm thinking:
- fetch is initiated when element is inserted into the document
- fetch is cancelled when element's href attribute is modified
  - 'cancelled' is subject to type of hint.. some are MUST, others are not.

**Comment by igrigorik** [comment]
For housekeeping, from https://bugzilla.mozilla.org/show_bug.cgi?id=1135160#c32:

> Does it matter where in the DOM the element lives? I.e. if it's inserted into the head or into the body, or somewhere else. Making this explicit in the spec would be good.

No, location should not matter. Will make it explicit in the update.

**Comment by igrigorik** [comment]
@smaug---- @sicking PTAL at ccc73a1. Does that cover what we need?

**Comment by igrigorik** [comment]
Closing, addressed in 6f2d5c4 & 5e2ecc90754bd46401dfa4765afc2ed3d17b21a7.
