### ISSUE TITLE
`next`/`inert`are not future friendly

### ISSUE THREAD

**Issue by yoavweiss** [w3c/resource-hints#26]
As we discussed last week, the way `next` and `inert` are defined makes it impossible to ship without them and adding them later on (and also makes it impossible to add new such attributes in the future).

We need to figure out a way to define them in a way that's more future friendly (e.g. unknown attributes cause the whole link to get dropped).

**Comment by yoavweiss** [comment]
Or what @tabatkins [said](http://ircbot.responsiveimages.org/bot/log/respimg/2015-03-05#T117616)

**Comment by toddreifsteck** [comment]
Pasting quote to ensure it is obvious--
TabAtkins: If you can figure out how to coalesce types of preload requests, you can adopt the same kind of behavior CSS does - allow them to specify the same thing multiple times, where more primitive versions come first, and best version is last; last one the browser understands is used

**Comment by igrigorik** [comment]
Closing, let's continue in #27.
