### ISSUE TITLE
Add "Implementation Considerations" section

### ISSUE THREAD

**Issue by igrigorik** [w3c/resource-hints#31]
- Discuss ServiceWorker + `as` interop for prefetch/prerendering - e.g. the routing may differ based on specified context (https://github.com/w3c/resource-hints/pull/30#issuecomment-98161652)
- Matching of hint responses with requests (https://github.com/w3c/resource-hints/issues/2#issuecomment-97720053) - interaction with caching policies, timeouts, allowing requests to continue across navigations.
  - Chrome behavior: matched unless no-store, retained for up to 5 minutes.

**Comment by sleevi** [comment]
Also want to discuss dns-prefetch (added from Issue #37 ) and the privacy implications regarding it. For example, see https://www.chromium.org/developers/design-documents/dns-prefetching for some of the discussion.

**Comment by igrigorik** [comment]
Matching should probably preload's cache definition and algorithm. Blocked on: https://github.com/w3c/preload/issues/30

**Comment by yoavweiss** [comment]
Getting back to this after many many years...
https://github.com/w3c/preload/issues/30 is actually being defined and should land shortly.
For the rest, #86 seems more specific, so closing this one.
