### ISSUE TITLE
Explain preconnect in terms of Fetch

### ISSUE THREAD

**Issue by sleevi** [w3c/resource-hints#34]
There's a disconnect right now between how a rel="preconnect" behaves and how that aligns to the equivalent fetch operation from https://fetch.spec.whatwg.org 

That is, preconnect exists to 'warm up' the connection used as part of the [HTTP network fetch](https://fetch.spec.whatwg.org/#http-network-fetch) phase of Fetch, specifically step 1. The inputs for such an operation are the optional _credentials flag_.

The _credentials flag_ is an internal implementation detail of Fetch (more clearly noted in [HTTP network or Cache Fetch](https://fetch.spec.whatwg.org/#http-network-or-cache-fetch) ), whose value is computed during the [HTTP fetch](https://fetch.spec.whatwg.org/#http-fetch) stage of Fetch

The following text from Fetch explains the conversion

> Let _credentials_ flag be set if either request's credentials mode is "`include`", or request's
> credentials mode is "`same-origin`" and the _CORS flag_ is unset, and unset otherwise.

There's a disconnect in the HTML spec's [description of the _crossorigin_ attribute](https://html.spec.whatwg.org/#cors-settings-attribute) and how that affects fetch, mostly because HTML isn't fully referring to Fetch, but the concept is hopefully clear - "anonymous" is equivalent to setting _omit credentials flag_ (HTML terms), which is most roughly equivalent to setting the Request's  [_credentials mode_](https://fetch.spec.whatwg.org/#concept-request-credentials-mode) to `omit` (Fetch terms).

The reason I raise this is to ensure that when setting a _crossorigin_ attribute on a rel="preconnect", the concepts can be clear as to how they align with Fetch's HTTP Network Fetch phase 1, and in particular, the distinct pools that exist that are exclusively keyed off the Fetch _credentials flag_.

Explaining in terms of HTML Standard, as done currently, leaves ambiguity, because there isn't a described Request object as there is in Fetch, and rel="preconnect" isn't described in terms of HTML's (outdated) [CORS-enabled fetch](https://html.spec.whatwg.org/#potentially-cors-enabled-fetch). As a result, there's an impedance and terminology mismatch.

**Comment by annevk** [comment]
@sleevi I think HTML's "anonymous" is equivalent to credentials mode "same-origin", at least in some implementations. (I would prefer it though if we could make it "omit" everywhere.)

I think you're correct otherwise. HTML et al really need to be updated, not sure when @Hixie will get to that.

 (I wish there was a way we could make the multiple connection situation all this implies less sucky by the way, but I guess we need to discuss that elsewhere.)

**Comment by igrigorik** [comment]
From https://github.com/whatwg/fetch/issues/114:

> I think it (preconnect) needs to be a separate API since what it seems to be doing is essentially establishing a connection of sorts. Whereas Fetch might grab such a connection if it exists, or establish a new one otherwise. And even that is not really Fetch' purview, that is more HTTP which takes care of that. And WebSocket presumably has something similar.

That seems right to me. With that in mind, this bug is a subset of the broader pre\* JS APIs (https://github.com/w3c/resource-hints/issues/36). Closing this, let's continue the discussion there.

**Comment by sleevi** [comment]
I don't agree that these two are related. Closing this in terms of #36 just makes that bug all the more troubling.

It would seem far more productive to define preconnect in terms of Fetch and then, indepdently, evaluate whether or not it should be exposed. I'm very concerned that the API discussion will lead to a worse implementation, nor explain the reality of what today's UAs do / should do.

**Comment by annevk** [comment]
@sleevi I agree. Could you explain if an implementation today would invoke Fetch for preconnect. Or do both Fetch and preconnect invoke something further down? It would make sense to me if it's the latter, and if it's the latter I guess we need to expose that hook in Fetch somehow.

**Comment by igrigorik** [comment]
@sleevi @annevk fair points, reopening. Thinking out loud, to define this we'd have to...
1. Define _socket pool_ and why we have different pools for [some requests](https://www.w3.org/Bugs/Public/show_bug.cgi?id=26556#c3)
2. Define how Request is matched to appropriate pool and then bound to a socket
   - if no socket is available for that origin: initiate handshake, place it in pool, bind it to request.
     - the logic here also differs based on protocol in use (e.g. h1 vs h2 sockets)

Intuitively, seems like this is something Fetch would invoke as first step after checking appropriate application caches. Preconnect, in turn, would call that step directly and return right before "bind to request" step.. Anything else?

_p.s. it does seem like something that ought to [live in Fetch](https://github.com/whatwg/fetch/issues/114#issuecomment-134688424)._

**Comment by sleevi** [comment]
@annevk wrote:

> Or do both Fetch and preconnect invoke something further down?

Yes, I think that's the right way of thinking about it. I think we've got the building blocks correct in [HTTP-network fetch](https://fetch.spec.whatwg.org/#http-network-fetch) from Fetch, and it's a matter of breaking that out into a separable step which preconnect could then expose.

@igrigorik I actually don't think it's necessary (or wise) to expose/define socket pool, especially as browsers are already behaving differently. Regardless of whether we specify pools or how they're used, I do believe we want to clearly specify what the external expectations are as to what a rel="preconnect" will do. That is, that there's a credentials flag, that it has a particular interpretation, etc.

For example, Fetch doesn't specify how Keepalives are used, or how H2 connection pooling is used,  or about maximum socket limits, or HPKP, and I think those are both fine and right for what Fetch tries to do (and my love of the Extensible Web Manifesto does not extend to trying to explain these, as the more you do the less flexibility implementations have to optimize/experiment).

My primary goal is making sure it's clearly explained how the network state/behaviours for a rel="preconnect" relate/apply to a HTTP-Network Fetch.

Conceptually, and this is likely to be poorly done, it might make sense to think of there being some RequestProperties object, which is the grouping key for connections. Fetch would perform an HTTP Request using a connection that had the same RequestProperties. rel="preconnect" would 'do something', and the result (if the UA even decided to 'do something') would be a connection that had the same RequestProperties as those constructed from the rel="preconnect" tag.

I'm being intentionally vague on 'do something' - because the UA might decide not to make a connection (e.g. connection limits), might have other information influencing it (e.g. @mnot's Browser Hints exploration), might be locally constrained (e.g. proxy connection limits), any number of things - but the goal is that IF there is a change due to rel="preconnect", then it has a clear and unambiguous state.

**Comment by igrigorik** [comment]
> Yes, I think that's the right way of thinking about it. I think we've got the building blocks correct in HTTP-network fetch from Fetch, and it's a matter of breaking that out into a separable step which preconnect could then expose... Conceptually, and this is likely to be poorly done, it might make sense to think of there being some RequestProperties object, which is the grouping key for connections. Fetch would perform an HTTP Request using a connection that had the same RequestProperties. rel="preconnect" would 'do something', and the result (if the UA even decided to 'do something') would be a connection that had the same RequestProperties as those constructed from the rel="preconnect" tag.

That seems reasonable. That said, I'll defer to @annevk for the actual wording here; the update on RH end would be very simple.

**Comment by igrigorik** [comment]
Based on https://github.com/whatwg/fetch/commit/ee0950908d97a3a33698ea4bc89f73c0df069c2d, I'm thinking something like... 

To preconnect, the user agent must these steps:
- Let _origin_ be the origin [ORIGIN] of the URL value of the `href` attribute.
- Let _credentials_ be a boolean value set to `true` if the `crossorigin` CORS setting attribute is set to `use-credentials`, and set to `false` otherwise.
- [Obtain connection](https://fetch.spec.whatwg.org/#concept-connection-obtain) with _origin_ and _credentials_. 

WDYT?

**Comment by sleevi** [comment]
@igrigorik There's no guarantee based on a preconnect hint that a UA will `obtain connection`, so I do think it may need to be a bit more flexibly worded. But as far as the preconnecting part, that sounds right.

**Comment by sleevi** [comment]
@igrigorik I should add that there's also cases where a 'full' connection may not be established.

For example, in the event of a TLS client auth scenario, a disconnected socket will be left in Chrome's socket pool with a sigil-marker that whoever gets the socket out of the pool needs to prompt the user, and then they need to get a _new_ socket [I don't recall with Chrome's priority whether we actually preempt priorities with highest, or if we just re-enter the request with the now completed auth-details and leave it as a new request] to actually fully establish `connection`. Just another area where the flexibility here helps, since Firefox does TLS client authentication prompting at a different phase and w/ a different set of timers & behaviours.

**Comment by annevk** [comment]
> Let credentials be a boolean value set to true if the crossorigin CORS setting attribute is set to use-credentials, and set to false otherwise.

Given that `crossorigin` defaults to "`same-origin`" for credentials mode you'll need to do some origin comparison as well, I think.

**Comment by igrigorik** [comment]
Thanks guys, ptal at https://github.com/w3c/resource-hints/pull/45. 

@sleevi I think the text below processing steps should ~cover the scenario you described?
