### ISSUE TITLE
dns-prefetch on HTTPS pages

### ISSUE THREAD

**Issue by yoavweiss** [w3c/resource-hints#46]
It seems that as far as implementations go, most of them limit `dns-prefetch`support on HTTPS pages:
- In Chrome, dns-prefetch is not supported for HTTPS pages, unless a [`X-DNS-Prefetch-Control`](https://www.chromium.org/developers/design-documents/dns-prefetching#TOC-DNS-Prefetch-Control) header is used by the page.
- The same is true for Firefox, with the [same opt-in mechanism](https://developer.mozilla.org/en-US/docs/Web/HTTP/Controlling_DNS_prefetching#Turning_on_and_off_prefetching) in place.
- Looking at the code, same is true for WebKit as well.
- I'm not aware of a similar limitation for IE/Edge.

The reasoning given by the various blog posts is that this mechanism prevents data leak of hosts inside `<a href>` links on that page. I believe that  `<a href>` dns prefetching was wrongfully coupled to `<link rel=dns-prefetch>` in all those implementations, and should be decoupled.

There's no immediate spec action to be taken, since I believe the implementations should change rather than the spec.

**Comment by igrigorik** [comment]
>  I believe that `<a href>` dns prefetching was wrongfully coupled to `<link rel=dns-prefetch>` in all those implementations, and should be decoupled.

I agree. The inclusion of a `<link rel=dns-prefetch ...>` is explicit opt-in by the origin, there is no reason to impose other control mechanisms. The `X-DNS-Prefetch-Control` is for UA-initiated *-prefetch.

/cc @mikewest @sleevi for sanity check.

**Comment by sleevi** [comment]
Yeah, I mentioned to @yoavweiss that this sounds reasonable and that I can't think of any (new) issues.

**Comment by igrigorik** [comment]
@yoavweiss I think next steps here are to open bugs against implementations? I don't believe there is anything actionable here as far as spec is concerned?

**Comment by yoavweiss** [comment]
Yeah, closing.
