### ISSUE TITLE
The spec uses "navigation context" as if it was some term defined somewhere

### ISSUE THREAD

**Issue by smaug----** [w3c/resource-hints#48]
For example
"With dns-prefetch and preconnect relations to indicate probability of initiating a fetch against the specified origin, either within the current navigation context, or within the next navigation context."
doesn't really mean anything since 'current navigation context' and 'next navigation context' aren't actually defined anywhere.
'navigation context' sounds similar to 'browsing context', but is clearly something very different.

**Comment by yoavweiss** [comment]
Seems like this will be solved by #86

**Comment by yoavweiss** [comment]
Solved (and moved to HTML)
