### ISSUE TITLE
It is not clear whether <link rel="dns-prefetch"> in a document which doesn't have browsing context should do something

### ISSUE THREAD

**Issue by smaug----** [w3c/resource-hints#49]
Should
document.implementation.createHTMLDocument().body.innerHTML = "&lt;link rel="dns-prefetch" href="http://www.foo.bar"&gt;" do something?

**Comment by smaug----** [comment]
As an example from HTML spec, it has the following for &lt;img&gt;
" The element's node document must be the active document of the browsing context of the Window object on which the interface object of the invoked constructor is found."

**Comment by igrigorik** [comment]
We need to mirror http://w3c.github.io/preload/#dfn-appropriate-times for RH.

**Comment by smaug----** [comment]
This applies also to other resource hints. Currently per spec any document from XHR for example should trigger the hints.

**Comment by smaug----** [comment]
Looks like  http://w3c.github.io/preload has the same bug.

**Comment by igrigorik** [comment]
From https://html.spec.whatwg.org/#the-link-element:

> The activation behaviour of link elements that create hyperlinks is to run the following steps:
> - If the link element's node document is not fully active, then abort these steps.

As such, I think this should already apply to all RH + Preload hints. Do we want to mirror this in these specs?

**Comment by smaug----** [comment]
activation behavior isn't about the stuff resource hints are about, but yes, we need something like that for rh + preload.

**Comment by clelland** [comment]
Now that this is in HTML, the relevant issue is https://github.com/whatwg/html/issues/9015
