### ISSUE TITLE
"pr"

### ISSUE THREAD

**Issue by mnot** [w3c/resource-hints#5]
Some people may misread this as "priority" -- perhaps change to "prob" or "probability"?

**Comment by igrigorik** [comment]
- I was using `probability` before: clear, but painful to type out. 
- `pr` is a common acronym for probability: short, but has potential for ambiguity.
- `prob` is an in-between: short(er) but also not entirely clear either. =/

I'm ok with any one, but personally I'd prefer a shorter name.

**Comment by igrigorik** [comment]
So far haven't heard anyone scream about the shorter name, closing this.. feel free to reopen if you feel strongly about it.

**Comment by yoavweiss** [comment]
+1 to `prob` :)

**Comment by ashumeow** [comment]
pr = priority
prob = probability
:+1:

**Comment by mnot** [comment]
♥️ it.

**Comment by Jxck** [comment]
lots of misread happens around me.
+1 to `prob`

**Comment by igrigorik** [comment]
FWIW, so far the implementations have skipped `pr` entirely.. which is a signal that this may be an at-risk feature.

**Comment by bizzbyster** [comment]
Is "prob" being implemented?

**Comment by igrigorik** [comment]
No. Upcoming release of preconnect (in Chrome and FF) do not implement
pr/prob. There is a preload implementation underway in Chrome, and same
story there.

**Comment by yoavweiss** [comment]
As the implementer in Blink, I'm not opposed to adding a `pr`/`prob` (I like `prob` better :D), but it'd require some thinking around how to implement it properly (we would need some heuristics on when to preconnect/preload based on the browser's env).
So, I think that it can be something implementation add later on, once the basic functionality ships and proves to be stable, and once we'd have enough browser env data (e.g. connection speeds) to use it properly.

**Comment by bizzbyster** [comment]
Sounds good.
