### ISSUE TITLE
https://w3c.github.io/resource-hints/#dns-prefetch doesn't define what dns-prefetch should do

### ISSUE THREAD

**Issue by smaug----** [w3c/resource-hints#50]
preconnect case has DNS lookups etc., but dns-prefetch says just
"The dns-prefetch relation is used to indicate an origin that will be used to fetch required resources, and that the user agent SHOULD resolve as early as possible."

**Comment by igrigorik** [comment]
What would you like to see here? We don't have any plumbing in Fetch (or anywhere else for that matter) to initiate a DNS lookup.

/cc @annevk

**Comment by smaug----** [comment]
Well, at least it should hint something about DNS usage? Like that a DNS lookup might happen :)

**Comment by annevk** [comment]
Yeah, just saying it does a DNS lookup of which the result can be reused is probably sufficient for now. (And perhaps ignoring non-domain things, like IP addresses.)

**Comment by clelland** [comment]
Now that this is merged into HTML, the relevant issue is https://github.com/whatwg/html/issues/9015
