### ISSUE TITLE
overwrite, cancel or invalidate a prerendered page

### ISSUE THREAD

**Issue by adardesign** [w3c/resource-hints#51]
Lets say In the HTML I am prerendering a page like this:

`<link rel="prerender" href="https://www.adorama.com/">`
This prerenders the next page behind the scenes and is shown instantly when the user navigates to this page.. 

But the problem is, What if after the prerendered page successfully prerendered, and now the user made a change in the original page that alters the way the next (pre-rendered) page should behave.

How can we invalidate that prerendered page, so when we view it first it will request a new page and not show the pre-rendered page.

Is there a way to invalidate, cancel or refresh the prerendered page?

**Comment by adardesign** [comment]
One way to do this is to have JS programmatically overwrite the `href` so it will request a new page.
But we don't want to overwrite the href, Because we want to benefit from client or CDN caching..

**Comment by adardesign** [comment]
The other way I can think of, is to have logic in the pre-rendered page to check for page visibility API and we can check if `visibilityState === prerender` and then add a event listener for on `visibilitychange` and on the event that `visibilityState === visible` we can check if the stored values (settings) are still the same and if not we can run the logic needed to render page correctly or simply refresh the page.....

But this is such a workaround, It would be great if we can inject a `<link>` tag something like
`<link rel="prerender-cancel" href="https://www.adorama.com/">` which invalidates, cancels or deletes the prerendered  page

**Comment by igrigorik** [comment]
Note that even without prerender the user can cmd-click (or equivalent) on a link and open some page in background (document.visibilityState == hidden). Then, they could do something on the original page that might affect content on the background page.. When the user switches, you have the same problem.

As such, your last approach is the right way to handle the case you're describing. Whenever page transitions to `visible`, you should check for updated settings, etc, and reflect them in the UI - e.g. use sessionStorage to propagate updates, retrieve latest values, etc.

Cancelling "prerender" is not the right solution here, as it ignores the larger class of related problems that have nothing to do with prerendering.

**Comment by adardesign** [comment]
Got it, you are right!

Thanks
