### ISSUE TITLE
Register link relations with IANA

### ISSUE THREAD

**Issue by dret** [w3c/resource-hints#52]
can we do the same here that we did over at https://github.com/w3c/preload/issues/41? if that's ok, i'll happily create a PR for that.

**Comment by igrigorik** [comment]
Yep!

**Comment by dret** [comment]
great, thanks. stay tuned...

**Comment by dret** [comment]
thanks for merging #53, next up is sending request to link-relations list...

**Comment by dret** [comment]
request sent to link-relations@ietf.org list: http://mailarchive.ietf.org/arch/msg/link-relations/UfMUcQQDJjyWkB5rAcp4jlRRx0E

**Comment by igrigorik** [comment]
Thanks Erik!

**Comment by dret** [comment]
some feedback from @reschke (http://mailarchive.ietf.org/arch/msg/link-relations/uHeHJ7RRsUyDZqM6e5_TaHsRwWI):

"My gut reaction is: why do we need a whopping 5 link relations (including preload)?
7.1 and 7.2 look very similar; they also need to talk about the link context's origin so that people are not tempted to insert just the origin.
7.3 and 7.4 look very similar as well; 7.4 also needs to be rephrased to be independent of the media type."

i tend to agree with 7.4: link relations should not hardcode dependencies on media types, that's tight coupling and bad design. not sure about how to address the other concerns, but definitely good to get some feedback about the "web surface" of the design.

**Comment by igrigorik** [comment]
- I've argued for 7.1 + 7.2 but was convinced otherwise: https://github.com/w3c/resource-hints/issues/37
- 7.3 prefetch is fetch only; 7.4 is fetch + execute: from an HTTP perspective yes they look the same, but they are different from a browsers perspective and we need to distinguish them - e.g. prerender will kick off other fetches.
- media type: this is specced to to reflect what's implemented, and prerender only meaningfully applies to HTML documents.

**Comment by dret** [comment]
there's a follow-up from @mnot on the list: http://mailarchive.ietf.org/arch/msg/link-relations/Kdc-9mWLEE8ClLHFwjhogxaOjik:

My .02 -

5988 doesn't require strong justification for registering a relation type; only that it follows certain rules. So, I'd say the fact that these relations went through an open process is enough to overcome any reluctance to register so many.

Talking about the context of the link is nice; see existing registry entries for examples.

WRT 7.4 - the applicable text in 5988 is:

"Registered relation types MUST NOT constrain the media type of the
   context IRI, and MUST NOT constrain the available representation
   media types of the target IRI.  However, they can specify the
   behaviours and properties of the target resource (e.g., allowable
   HTTP methods, request and response media types that must be
   supported)."

Putting RFC1918 language in registry entries is a bit weird too.

So something like this would be clearer:

"Indicates a resource that might be required by the next navigation, and that user agents ought to fetch and execute to improve performance."

**Comment by dret** [comment]
suggesting to adopt @mnot's proposal in #54.

**Comment by dret** [comment]
merged #54.
