### ISSUE TITLE
If a resource is prefetched, what would `initiatorType` show up as in ResourceTiming entries?

### ISSUE THREAD

**Issue by bluesmoon** [w3c/resource-hints#57]
If a resource is prefetched in a page using `<link rel="prefetch" href="foo.js" as="script"></link>`

and later on in the document, it is referenced using `<script src="foo.js"></script>`

If we then look up resource timing using `performance.getEntriesByName(".../foo.js")`, it is not clear what should happen:
1. Should there be 2 entries returned, with the first having `initiatorType` set to `link` and the second having it set to `script`?
2. What if the prefetch did not actually happen?
3. What if there was no `<script>` node
4. What if there is an error during the `prefetch`, but a retry during `<script>` is successful?

[Ref: https://www.w3.org/TR/resource-timing/]

**Comment by plehegar** [comment]
https://github.com/w3c/resource-timing/issues/8

**Comment by plehegar** [comment]
The proposal in https://github.com/w3c/resource-timing/issues/8 is to use "preflight" if I read there correctly.

**Comment by plehegar** [comment]
Following the trail, I ended in https://github.com/w3c/resource-timing/issues/39

**Comment by bluesmoon** [comment]
but isn't preflight for checking CORS?

**Comment by igrigorik** [comment]
Yeah, preflight is a separate beast.

> If a resource is prefetched in a page using `<link rel="prefetch" href="foo.js" as="script"></link>`
> and later on in the document, it is referenced using `<script src="foo.js"></script>`

FWIW, I think you meant to use "preload", not prefetch.. the latter is not guaranteed to happen, whereas the former is a high-priority fetch. Also, `as` is only defined on preload.

> Should there be 2 entries returned, with the first having initiatorType set to link and the second having it set to script?

Yes.

> What if the prefetch did not actually happen?

Then you'd see only one entry, which is the script tag that initiates the download.

> What if there was no `<script>` node

For prefetch, you _might_ see the request initiated by prefetch.. For preload, you _will_ see the request.

> What if there is an error during the prefetch, but a retry during `<script>` is successful?

See https://github.com/w3c/resource-timing/issues/12.

---

Stepping back, it seems reasonable to me to extend initiator to surface {prefetch, preload, prerender}.

**Comment by yoavweiss** [comment]
Right now it's defined as "link". If there's interest in changing that definition, that's something that can happen as part of prefetch's processing model definition.

**Comment by noamr** [comment]
Closing for now. As of now, Initiator type for `prefetch` is `link`.
