### ISSUE TITLE
Spec is horribly borked

### ISSUE THREAD

**Issue by domenic** [w3c/resource-hints#59]
https://w3c.github.io/resource-hints/ has large sections that have been put into `<pre>` blocks instead of output correctly.

**Comment by igrigorik** [comment]
Hmm, interesting. Pushed a "fix" to make it readable: https://github.com/w3c/resource-hints/commit/bb6a96088ba3e2aa65920c9ad54db2dc73a57c44

I suspect recent changes in https://github.com/w3c/respec/issues/724 might be the cause. /cc @marcoscaceres

**Comment by marcoscaceres** [comment]
My bad. Should be all good now.

**Comment by igrigorik** [comment]
Reverted. Thanks Marcos! Closing :)
