### ISSUE TITLE
Relationship with "Resource Priorities"

### ISSUE THREAD

**Issue by dret** [w3c/resource-hints#6]
it would be helpful to include some (probably informative) text about the relationship with "Resource Priorities" http://www.w3.org/TR/2013/WD-resource-priorities-20131029/, since there seems to be quite a bit of overlap in the targeted scenarios.

**Comment by plehegar** [comment]
Resource Priorities is abandoned, per
 http://lists.w3.org/Archives/Public/public-web-perf/2014Oct/0042.html
I updated the editor's draft but didn't have the time to update the /TR version yet. Will do asap.

**Comment by dret** [comment]
that was quick. so the /TR will move to NOTE status, right? anyway, thanks for the info!

**Comment by plehegar** [comment]
Yes, it will be a Note. I just sent a publication request for that effect in fact since I was on a roll :)

**Comment by laukstein** [comment]
Related feature request "make <img> elements not load their images until needed" https://www.w3.org/Bugs/Public/show_bug.cgi?id=17842
