### ISSUE TITLE
Fetching resource hint link with referrer policy

### ISSUE THREAD

**Issue by tungnh28** [w3c/resource-hints#61]
Specs [1] clarified some cases that we should obtain resource
In the case Referrer policy restriction is applied to prefetch (such as link.setAttbiute("referrerPolicy", "origin"), the fetching should follow the restrictions
[1] https://w3c.github.io/resource-hints/#fetching-the-resource-hint-link

There're 2 cases:
1)
var hint = document.createElement("link");
document.head.appendChild(hint); 
hint.rel = "prefetch"; //trigger obtain, but no href, ignore
hint.referrerPolicy = "origin"
hint.as = "html";
hint.href = "/article/part3.html"; //trigger obtain, fetching resource
This case referrer policy "origin" will be applied to fetching hint resource

2)
var hint = document.createElement("link");
document.head.appendChild(hint); 
hint.rel = "prefetch"; //trigger obtain, but no href, ignore
hint.as = "html";
hint.href = "/article/part3.html"; //trigger obtain, fetching resource  (A)
hint.referrerPolicy = "origin" //(B)

Obviously in case 2, referrer policy is not applied to fetching resource at (A).
Do you need to obtain resource again in case 2 at (B) ? Any advices? @igrigorik. Thank you so much

Referrer is already sent out(whatever it is) changing it to something else is too late and doesn't give any additional privacy. I assume that we do nothing in (B) this case

**Comment by igrigorik** [comment]
> Do you need to obtain resource again in case 2 at (B) ? Any advices? @igrigorik. Thank you so much.

I don't think so? As you said, you've already sent out the request, so... 

/cc @yoavweiss

**Comment by yoavweiss** [comment]
For images we resolved similar cases as a side-effect of the fact that we made their fetch async, but I don't think we should be doing the same here. Basically, developers should avoid such patterns.

I think we all agree that re-fetching that resource without a referrer helps no one.

**Comment by igrigorik** [comment]
I don't believe there is anything actionable here as far as RH spec is concerned. Closing, but feel free to reopen if you think otherwise.
