### ISSUE TITLE
Usage example for crossorigin use in Link header.

### ISSUE THREAD

**Issue by jdalton** [w3c/resource-hints#64]
I noticed that prefetch can specify crossorigin attirbute when using the link tag. Could there also be an example of handling it with the [Link: header](https://w3c.github.io/resource-hints/#h-fetching-the-resource-hint-link).

A follow-up would be expanding on what are the accepted values of `linkElement.crossOrigin=...`. Is it just string values or will a boolean `true` or an empty string `""` be treated as `"anonymous"`?

**Comment by yoavweiss** [comment]
The `crossorigin` attribute on link elements is identical to other elements. For values see https://html.spec.whatwg.org/#cors-settings-attributes or https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes

Adding it as an attribute to headers is identical to other attributes: e.g. 
`Link: <https://example.com/logo-hires.jpg>; rel=prefetch; as=image; crossorigin`
or
`Link: <https://example.com/logo-hires.jpg>; rel=prefetch; as=image; crossorigin=anonymous`

Do you think the spec is not clear enough on that front?

**Comment by jdalton** [comment]
Ya, I eventually put it together looking at other blog posts / references. With CORS being its own header initially I wasn't sure if that would be tackled somewhere else.

**Comment by staabm** [comment]
was also searching exactly that and found the example here.

I guess it would also be helpful for others to have a `crossorgin` example in the spec.
(I searched the spec before finding this issue via google)

**Comment by yoavweiss** [comment]
The behavior of Link headers and crossorigin is now defined in https://html.spec.whatwg.org/#processing-link-headers
If there's a need to further document `crossorigin` specifically, the relevant [MDN article](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link) is probably the best place.
