### ISSUE TITLE
If a cached resource provides resource hints, are they processed?

### ISSUE THREAD

**Issue by ithinkihaveacat** [w3c/resource-hints#65]
For example, when rendering a (cached) HTML page that contains

``` html
<link rel="preconnect" href="//example.com">
```

does the browser initiate a new network connection to `example.com`? Is the behavior the same if the `Link` HTTP header is used? Are `preload` hints applied recursively?

It's possible (likely?) that the connection to `example.com` would be "wasted" in this case--since the resources it provides may also be cached--however it's also possible that resources from `example.com` are required.

(This question may be related to #31.)

**Comment by igrigorik** [comment]
> does the browser initiate a new network connection to example.com?

Yes.

> Is the behavior the same if the Link HTTP header is used?

Yes.

> Are preload hints applied recursively?

Yes.

> It's possible (likely?) that the connection to example.com would be "wasted" in this case--since the resources it provides may also be cached--however it's also possible that resources from example.com are required.

Yes.

**Comment by ithinkihaveacat** [comment]
Thanks!

In that case, will resource hints negatively affect page load times if the hinted resources were available in the cache? (Unbeknownst to the client at the time the hint was processed.)

In particular, if the initial page load preloads fonts (which are then cached), are fonts (unnecessarily) preloaded again on subsequent page loads? Does HTTP/2 push have any solutions to this?

**Comment by yoavweiss** [comment]
Preconnect should not have a negative impact (it's not blocking).

I'm not sure what you mean regarding preload, but preloaded resources in the cache will be reused, so there is no negative impact to preload of cached resources.

**Comment by ithinkihaveacat** [comment]
Preconnect would still consume resources though, even if not blocking, though maybe they're negligible? (I wonder about setups like Google Fonts, in which CSS served by `fonts.googleapis.com` declares a preconnect to `fonts.gstatic.com`, which would seem to guarantee a connection to `fonts.gstatic.com` for every page that used Google fonts, even if the CSS and fonts themselves were already cached and nothing needed to be retrieved from network.)

To followup to my own question about interactions with HTTP/2, https://www.w3.org/TR/preload/ (which I just found) suggests disabling push for potentially-cached resources, in favour of allowing the client to process the resource hints: "For example, the server might omit initiating push if it believes that the response is available in the client's cache."

So in light of this, I'm unsure under what circumstances it makes sense to HTTP/2 push a cacheable resource.

**Comment by igrigorik** [comment]
> In that case, will resource hints negatively affect page load times if the hinted resources were available in the cache? (Unbeknownst to the client at the time the hint was processed.)

Depends on the hint and how you use it.
- Preconnect, as Yoav already explained, is not blocking and has minimal overhead -- for TLS, cost of the handshake.
- Prefetch/Prerender request does check the HTTP cache (same for preload).

> So in light of this, I'm unsure under what circumstances it makes sense to HTTP/2 push a cacheable resource.

When you believe that this may be client's first visit, etc. See "cache digests" discussion on the HTTP working group.

---

There is nothing spec-actionable here, closing.
