### ISSUE TITLE
Transition Level 1 to CR

### ISSUE THREAD

**Issue by igrigorik** [w3c/resource-hints#67]
- **Known / outstanding spec issues**
  - [ ] https://github.com/w3c/resource-hints/milestone/1
- **Web platform tests**
  - [ ] TODO, manual tests? 
- **Privacy and security**
  - [x] http://w3c.github.io/resource-hints/#security-and-privacy
- **Implementations**
  - [x] Chrome: dns-prefetch, preconnect, prefetch
  - [ ] Firefox: dns-prefetch, preconnect, prefetch
  - [ ] Edge: dns-prefetch, preconnect (only link header)
  - [ ] Webkit: dns-prefetch, preconnect (only HTML)
- **Public signals: adoption, feedback...**
  - dns-prefetch: https://www.chromestatus.com/metrics/feature/timeline/popularity/899
  - preconnect: https://www.chromestatus.com/metrics/feature/timeline/popularity/900
  - prefetch: https://www.chromestatus.com/metrics/feature/timeline/popularity/917
  - prerender: https://www.chromestatus.com/metrics/feature/timeline/popularity/918

**Comment by toddreifsteck** [comment]
Implementation updates:
Edge has a bug preventing prefetch from functioning properly and has not yet implemented prerender.
IE11 supports dns-prefetch, prefetch and prerender.

Our status page doesn't currently support IE11 having a feature and Microsoft Edge not having it or I'd update the status.... https://github.com/MicrosoftEdge/Status/issues/469

**Comment by toddreifsteck** [comment]
Made the same comment on preload. :-)
I know it is already in progress but I want to ensure that we are clear that the tests are super critical for this spec given its "background" nature. I assert that we MUST get tests into Web Platform Tests before moving this to the next phase.

**Comment by myakura** [comment]
regarding prerender, [Chrome team recently announced their intent on deprecating it](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/0nSxuuv9bBw). I wonder how this affects transition.

**Comment by yoavweiss** [comment]
The intent is to deprecate the internal backend for the feature, in order to replace it with a mobile-friendly one. There's no intent to deprecate the feature itself

**Comment by toddreifsteck** [comment]
TPAC 2017:
@yoavweiss has agreed to review the issues and estimate whether he can get this spec to CR in next quarter.

**Comment by toddreifsteck** [comment]
@plehegar 
TPAC 2017:
Discussion was had on how to ship this to CR assuming all issues are closed. Observing that these features work properly is difficult and could require much configuration of browsers. What is the path forward for dns-prefetch which is tricky to test or for prefetch which is conforming if a browser does not implement?

Lets discuss a conclusion on strategy on a future call.

**Comment by clelland** [comment]
Spec is merged into HTML; this isn't necessary anymore
