### ISSUE TITLE
as attribute is underspecified 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/resource-hints#7]
The `as` attribute is underspecified. The processing model for attribute values should more closely resemble similar attributes in HTML. It should be clear how to handle white space, it should be clear how to handle multiple values (e.g., "html css"). There should be a sensible default or an algorithm to define a sensible default.

**Comment by igrigorik** [comment]
@marcoscaceres this should be addressed by https://github.com/w3c/preload/pull/15 - ptal, let's continue there.
