### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by xfq** [w3c/resource-hints#71]
Some repos have both `LICENSE` and `LICENSE.md`:

* https://github.com/w3c/performance-timeline
* https://github.com/w3c/resource-timing/
* https://github.com/w3c/navigation-timing/

Some repos only have `LICENSE`:

* https://github.com/w3c/hr-time/

Some repos only have `LICENSE.md`:

* https://github.com/w3c/user-timing/
* https://github.com/w3c/page-visibility
* https://github.com/w3c/beacon/
* https://github.com/w3c/requestidlecallback/
* https://github.com/w3c/resource-hints/
* https://github.com/w3c/preload/

`LICENSE` files link to the [W3C Document License](http://www.w3.org/Consortium/Legal/copyright-documents), while `LICENSE.md` files link to the [W3C Software and Document Notice and License](http://www.w3.org/Consortium/Legal/copyright-software). IANAL, but they look like 2 similar but different licenses.

**Comment by igrigorik** [comment]
Good catch, not sure how we ended up with two variants.

@plehegar @siusin any guidance here? /cc @toddreifsteck

**Comment by siusin** [comment]
The charter says --
> This Working Group will use the W3C Software and Document license for all its deliverables.

I'll do a clean up on these repos later if it makes sense.

**Comment by siusin** [comment]
All the specs should be using the [W3C Software and Document license](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document) now.

**Comment by igrigorik** [comment]
Awesome, thanks @siusin!

**Comment by xfq** [comment]
Cool. I confirm that all repositories now links to the [W3C Software and Document license](http://www.w3.org/Consortium/Legal/copyright-software). Thank you, Xiaoqian!
