### ISSUE TITLE
Hinting HTTP Alternative Services

### ISSUE THREAD

**Issue by LPardue** [w3c/resource-hints#72]
## Context
This issue particularly targets the `preconnect` and `prefetch` relationship types.

Generally, I wonder how clients treat conventional Alt-Svc advertisements (RFC 7838) during these phases, and whether there is a possible optimisation that could be made by advertising Alt-Svc in the Link.

## Use case
Origin selection with these resource types can warm a HTTP/TCP connection in a single RTT. However, HTTP/QUIC may offer a more optimal path for client requests. 

Right now, there is no method to to explicitly identify a HTTP/QUIC endpoint; rather HTTP Alternative Service are used to advertise the endpoint from a HTTP/TCP origin. This means there is no way to indicate a HTTP/QUIC endpoint explicitly in these link relations and additional RTT is required.

* If `preconnect` is used and H2/TCP is negotiated with the origin, the client may learn about an HTTP/QUIC endpoint via an `ALTSVC` frame sent on the connection. I'm not 100% sure how clients would react to this but lets say that the client takes the hint, tests UDP connectivity and successfully opens an HTTP/QUIC connection during the preconnection phase. In such a  case, we've performed a preconnection on TCP that will effectively be thrown away.
* If `prefetch` is used, the client may learn about an HTTP/QUIC endpoint via an `Alt-Svc` header attached to the response. I'm not 100% sure how clients would react to this, perhaps the Alternatives are put on hold and only tested on subsequent requests to the origin? Assuming such a strategy, the testing and selection of HTTP/QUIC is postponed until a subsequent request.

## Proposal
RFC 7838 defines origins and alternatives as tuples, and an ABNF header form e.g.

|   | Tuple | Header form |
| ------------- | ------------- | ------------- |
| origin  | `("http", "www.example.com", "80")`  |  N/A |
| alternative  | `("hq", "hq.example.com", "50781")`  | `Atl-Svc: hq="hq.example.com:50781"` |

As a starting proposal, I suggest that alternatives are articulated in a new extension target attribute (strawman name `alt-svc`) that could be expressed alongside relevant Link relationship types (TBD). Repetition of the `alt-svc` attribute is allowed and follows the guidance in RFC 7838. Factors to consider and work out are quote escaping and alt-svc parameters. An example of how this would are:

Simple case
```
<link rel="preconnect" href="//www.example.com" alt-svc="hq=\"hq.example.com:50781\""> (how to escape double quotes correctly?)
Link: <https://example.com>; rel=preconnect; alt-svc="hq=\"hq.example.com:50781\""
```

Alt-Svc with params
```
<link rel="preconnect" href="//www.example.com" alt-svc="hq=\"hq.example.com:50781\"; ma=600"> (how to escape double quotes correctly?)
Link: <https://example.com>; rel=preconnect; alt-svc="hq=\"hq.example.com:5078\"; ma=600"
```

On reception of the `alt-svc` attribute, clients behave in accordance with RFC 7838 (and Resource Hints). Clients use this information as a hint an implement their own strategies for selection. Using HTTP/QUIC as an example, a race is carried out and the winner is selected as the preferred option.

## Security considerations
This proposal effectively allows origin A to advertise an alternative for origin B, which introduces some new security considerations that need to be explored. Careful wording around security context awareness, and checks/measures may mitigate concerns. However, the proposal may be unachievable in practice, I hope to gain some additional input on the topic to determine the answer.

## Closing
The proposal fills a gap where HTTP/QUIC endpoints cannot be expressed directly, thus requiring a tightly coupled HTTP/TCP endpoint to advertise their existence. The gap is especially prevalent for  `preconnect` where only ATSVC can be used, restricting the capability to H2 or requiring an additional request/response.

Using the Link header to articulate the same Alt-Svc information provides the opportunity for weak coupling by having one origin advertise a different origin and it's alternatives. This may introduce unacceptable security concerns

**Comment by LPardue** [comment]
@yoavweiss I forgot I raised this ticket. I think the use case is still valid. Any thoughts?

**Comment by yoavweiss** [comment]
Over 5 years later, I bumped into this... Apologies for the delay :/

Is this use case still something that can be useful?

**Comment by LPardue** [comment]
I'd have to brush up my understanding of the OP. Some stuff has changed in the meantime. Things like the HTTPS RR can signal facets of a zone are available (like what HTTP versions it supports) during DNS resolution.

Furthermore, the HTTP WG is currently working on a is of RFC 7838 (Alt-Svc) definition, so it might be that we should revisit this in the same swoop.

**Comment by LPardue** [comment]
The more I think about this, the proposal has downsides that are probably intractable. 

Given its an old issue with no other supporters, I suggest closing this.

**Comment by yoavweiss** [comment]
Thanks! Closing makes sense. We can always re-open if things change in the future.
