### ISSUE TITLE
Ensure X-DNS-Prefetch-Control is defined (or removed everywhere)

### ISSUE THREAD

**Issue by annevk** [w3c/resource-hints#75]
See findings by @samuelhorwitz at https://github.com/whatwg/fetch/issues/658#issuecomment-356093141.

It seems this would require integration with HTML's navigate algorithm (assuming it only applies for such document resources).

It would also be good to figure out if that `<meta>` element is actually supported (and maybe file a bug to get that removed as it's only one browser).

**Comment by yoavweiss** [comment]
AFAICT, Chromium does support this header, as well as its http-equiv.

Should be defined as part of #86 

/cc @noamr

**Comment by yoavweiss** [comment]
AFAICT, Chromium does support this header, as well as its http-equiv.

Should be defined as part of #86 

/cc @noamr

**Comment by yoavweiss** [comment]
AFAICT, Chromium does support this header, as well as its http-equiv.

Should be defined as part of #86 

/cc @noamr

**Comment by yoavweiss** [comment]
Closing as this is being archived. Moved to https://github.com/whatwg/html/issues/9473
