### ISSUE TITLE
Recursive prefetch or similar-origin prerender

### ISSUE THREAD

**Issue by jyasskin** [w3c/resource-hints#77]
In working on https://amphtml.wordpress.com/2018/01/09/improving-urls-for-amp-pages/, we're expecting some use of `<link rel="prefetch" src="signed-html-exchange">` where it's likely to be useful to recursively prefetch subresources mentioned by `Link: rel=preload` headers within the [signed response](https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html).

To meet AMP's privacy requirements, the browser must only fetch resources from origins the prefetching page has opted into. For example, `https://searchengine.com/` might prefetch from `https://searchenginesfriend.com/`, and those resources should be able to recursively prefetch from `https://searchenginesfriend.com/` or `https://searchengine.com/`, but they shouldn't be able to prefetch from `https://sneakytracker.com/`.

This looks like either a recursive [prefetch](https://w3c.github.io/resource-hints/#prefetch) or a [prerender](https://w3c.github.io/resource-hints/#prerender) that's constrained to same- or [similar](https://html.spec.whatwg.org/multipage/browsers.html#unit-of-related-similar-origin-browsing-contexts)-origins.

1. Does it make sense to let `prefetch` do this by default? It currently seems to be forbidden by "SHOULD NOT apply preprocessing on the response", and if we remove that I'd want to make the similar-origin restriction explicit.
2. If not, should we add a `recursive` flag to `prefetch` or a `similar-origin` flag to `prerender`, or something else?

Thanks.

@cramforce @kinu @nyaxt

[Edit: I initially said the subresources would be `Link: rel=prefetch`, but @kinu pointed out that this didn't make sense: those were resources for the prefetched page, not resources that might be needed after a second click.]

**Comment by yoavweiss** [comment]
I wouldn't consider fetch of Link rel=preload headers to be "preprocessing". Generally, I think Link headers on prefetch resources should be processed as part of the fetching process. (which emphasizes that fact that we need to better define Link header processing as part of Fetch)

**Comment by cramforce** [comment]
I'm wondering: Why would this need to be origin constraint? Is there a security goal or only a privacy goal? The privacy goal may be achievable by simply ensuring that a resource only has desired preload headers.

Please define as to whether same/similar-origin-ness would apply to the origin of the web package or the packaged resource.

**Comment by kinu** [comment]
(After chatting with several others) I think we're reaching to a consensus that the spec just implies that this should just work, while the spec text for how preloads that come with cross-origin prefetches should be handled may need a bit more clarification.

**Comment by yoavweiss** [comment]
@noamr - should this be defined explicitly as part of https://github.com/whatwg/html/pull/7622 ?

**Comment by noamr** [comment]
This is handled in speculationrules and not here.
