### ISSUE TITLE
Where can `as` and `loadpolicy` attributes be used?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/resource-hints#8]
The spec needs to be more explicit about the elements in which the `as` and `loadpolicy`  attributes can be used (i.e., are they restricted exclusively to `link`?). Also, I recommend that you make those attributes into proper sections in the spec (so they are easy to find in the ToC).

**Comment by igrigorik** [comment]
Yes, restricted to `<link rel=preload>`, will update the spec - thanks.

**Comment by ashumeow** [comment]
How about this one?

```
<link rel="preload" href=" ">
```

**Comment by igrigorik** [comment]
Should be addressed in https://github.com/w3c/preload/pull/15/files.
