### ISSUE TITLE
Dead references to `pr` attribute

### ISSUE THREAD

**Issue by jakub-g** [w3c/resource-hints#81]
Hello,

I was reading the spec and noticed the references to `pr` attribute in the two lines

https://github.com/w3c/resource-hints/blob/gh-pages/index.html#L261-L263
https://github.com/w3c/resource-hints/blob/gh-pages/index.html#L281

It seems that `pr` was removed in this PR (pun intended): https://github.com/w3c/resource-hints/pull/76 but the dead references were left in the spec.

Should the first sentence be reworded, and the second removed altogether? I can volunteer to send a PR (or feel free to do it yourselves of course).

Regards,
Jakub

**Comment by yoavweiss** [comment]
Thanks for pointing that out :) Happy to accept a PR on that front, if you're interested in contributing.
