### ISSUE TITLE
Break Resource Hints into 4 specs

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/resource-hints#84]
Discussed at TPAC 2018:
* Because all 4 Resource Hints ONLY share the fact that they are speculative, @yoavweiss proposes we break them into 4 specifications.
* link rel dns-prefetch
* link rel preconnect
* link rel prefetch
* link rel prerender
* Any new speculative link rel tags would get their own specs.
* We will keep in mind that it is possible that we need to join these specs again for items such as the integrity attribute or other "shared behaviors" if they cannot be specified in the HTML5 or fetch specifications and must be specified here.

**Comment by clelland** [comment]
Spec is merged into HTML; this isn't necessary anymore
