### ISSUE TITLE
Implementing rel="preconnect"

### ISSUE THREAD

**Issue by nous3k** [w3c/resource-hints#85]
Hey,

I would like to ask something about implementing rel="preconnect". Can I implement It across the whole website? I mean: what happens if the connection is already resolved but user lands to another page with rel="preconnect"? Will the browser ignore this row or It will "reconnect"?

Thanks a lot

**Comment by yoavweiss** [comment]
Typically browsers coalesce connection requests, so if it'll encounter a preconnect request to a host it already has an established connection to, that should be a no-op.
