### ISSUE TITLE
It's not clear how preconnect would be used for redirects

### ISSUE THREAD

**Issue by crenshaw-dev** [w3c/resource-hints#87]
As far as I know, HTTP 30_ responses (redirects) don't return response bodies. So the "Anonymizing redirects" section must refer to either 

1. a 200 response occurring before expected redirects or 
2. a 30_ response with "Link" header(s).

[As far as I can tell](https://stackoverflow.com/questions/55381080/do-browsers-use-resource-hint-link-headers-in-redirect-responses), Link headers have no effect when placed in 30_ responses. 

I haven't tested with a 200 response containing something like `window.location = 'https://example.com/redirect';`. My guess is it will behave the same as the 302 if the navigation occurs immediately on load.

Either way, this section feels like it could use clarification, maybe a code example.

**Comment by noamr** [comment]
This is fully specified in the HTML spec. Early hints work on redirect responses, regular link headers don't. Covered in WPT
