### ISSUE TITLE
pr values are hard

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/resource-hints#9]
I would recommend you don't use `q`-style values for the `pr` attribute - they are notoriously difficult to combine and get right. If you want to have this, then make it something like 3 simple choices: 
- low, medium, high 

Or, you could even just make it a binary option, as it defaults to "high" (1.0) anyway. So you could just have a `low` attribute... or just reuse `defer` or something similar:

```
<link rel="prefetch" href="thing" low>
```

**Comment by igrigorik** [comment]
We started with {low, medium, high}, but based on feedback moved to numeric range - see https://github.com/igrigorik/resource-hints/issues/17#issuecomment-51434111.

I agree with you, pr=[0.0-1.0] may be an overkill. That said, we do need a mechanism to indicate relative probability of a hint, specifically for cases where multiple hints are present... Hmm.

**Comment by marcoscaceres** [comment]
Ok, I guess this will work itself out over time.
