### ISSUE TITLE
Prefetch and Cross-Origin-Opener-Policy / Cross-Origin-Embedder-Policy

### ISSUE THREAD

**Issue by annevk** [w3c/resource-hints#90]
This comes down to lack of integration with Fetch, but is worth discussing separately due to upcoming new features.

Where is prefetch supposed to be stored?

Depending on where it is stored, COOP+COEP might either wipe it away on navigation or might have to be enforced properly when doing a cache lookup as otherwise it can be used as a way to smuggle a cross-origin opaque response without CORP into a COOP+COEP process.

cc @yutakahirano @youennf @cdumez @ddragana

**Comment by youennf** [comment]
In WebKit, a prenavigate resource is expected to be stored in the networking process.
The plan is to wipe this resource on navigation if not actually used by the navigation.

It makes sense to me to enforce the usual security checks whenever a prenavigate cache hit happens. Enforcing CORP for those loads will currently be a no-op, which is fine.

**Comment by annevk** [comment]
Yeah, that makes sense for prenavigate and I wasn't too worried about that one. This is mainly if we keep prefetch around, which I understand can also be used to fetch subresources for the document you navigate next to (and maybe sometimes for workers for the current document? it's a bit of a mess).

**Comment by youennf** [comment]
I think prefetch resources also fit naturally in the networking process.
I would reuse the same security checks when hitting this cache as when hitting the HTTP cache.

I am not sure in that context what wiping-on-navigation exactly means though.
A user agent might decide to wipe them on cross-origin navigation or after some time, cancel some existing prefetch loads, but this seems user-agent specific behavior.

**Comment by annevk** [comment]
Yeah, if prefetch ends up in networking it should probably work out fine as Fetch will do the check for the CORP header from a COEP: require-corp document/worker. If it's some kind of "memory" cache however as with preload there might be issues.

**Comment by noamr** [comment]
This is specified fully now. Feel free to reopen if something is missing.
