### ISSUE TITLE
"prerender" visibility state is not defined

### ISSUE THREAD

**Issue by nhiroki** [w3c/resource-hints#94]
The [Resource Hints spec](https://w3c.github.io/resource-hints/#prerender) requires a prerendering page to have "prerender" visibility state like this:

> When prerendering a document the user agent MUST set the document's visibilityState ([PAGE-VISIBILITY]) value to prerender.

However, the [Page Visibility Level 2 spec](https://w3c.github.io/page-visibility/#visibility-states) doesn't define the "prerender" visibility state.

Should we use "hidden" visibility state in the Resource Hints spec or define the "prerender" visibility state in the Page Visibility spec?

**Comment by clelland** [comment]
Prerender has moved to https://wicg.github.io/nav-speculation/, and didn't follow this spec's move into HTML.
