### ISSUE TITLE
Question: Is preconnect needed when the resources are cached?

### ISSUE THREAD

**Issue by ittaibaratz** [w3c/resource-hints#96]
Consider the following use case:

1. The same domain is used for both static and dynamic resources.

2. All the static resources (That are present in the HTML) are cached (In my case they are managed by a service worker).

3. The dynamic resources (i.e. a POST request to a backend API) are not managed by a service worker and are not cacheable.

The question is - Will a preconnect help in this scenario? I am asking because the browser will already see the domain when it processes the HTML (i.e. `<link rel="stylesheet" href="https://mydomain/index.css">`) , but I guess it won't connect to it since the resource is in cache, or will it?

**Comment by noamr** [comment]
Preconnect will not help in this scenario, only when there is an actual HTTP/QUIC connection. Closing as this is not actionable :)
