### ISSUE TITLE
Allow QUIC and HTTP/3 connections via Preconnect

### ISSUE THREAD

**Issue by flano-yuki** [w3c/resource-hints#97]
> Initiating an early connection, which includes the DNS lookup, TCP handshake, and optional TLS negotiation, allows the user agent to mask the high latency costs of establishing a connection.

In the current text, Preconnect allows TCP + TLS connections, but there is no mention of QUIC or HTTP/3.

I think a user-agent that knows the server supports HTTP/3 by alt-svc can preconnect to the server with QUIC.

thx

**Comment by noamr** [comment]
There is no distinction between TCP and QUIC in the way this is now standardizes in the HTML/Fetch specs. closing
